version: "3.8"

services:
  php:
    build: .
    container_name: php_native_app
    ports:
      - "8100:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db_exam_1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3304:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
